//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class AppoCreate_Result1
    {
        public string description { get; set; }
        public string status { get; set; }
        public string id_cus { get; set; }
        public Nullable<System.DateTime> appointment_date { get; set; }
    }
}
