//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class getInforTrans_Result2
    {
        public string name_cus { get; set; }
        public string phone_cus { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> room { get; set; }
    }
}
