//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public string id_proj { get; set; }
        public string name_project { get; set; }
        public Nullable<int> id_real_estate_type { get; set; }
        public string address { get; set; }
        public string license_number { get; set; }
        public Nullable<System.DateTime> dateOfIssue { get; set; }
        public string PlaceOfIssue { get; set; }
    
        public virtual realEstateType realEstateType { get; set; }
    }
}
